language: python
python:
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libxml2-dev libxslt1-dev python-dev lib32z1-dev
install: "pip install -r requirements.txt"
script: PYTHONPATH=site nosetests test
